# Generated by Django 5.0.7 on 2024-07-17 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorcarouselitem',
            name='carousel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='posts.colorcarousel'),
        ),
        migrations.AlterField(
            model_name='maincarouselitem',
            name='carousel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='posts.maincarousel'),
        ),
    ]
