# Generated by Django 5.0.7 on 2024-08-12 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_sizecarouselimage_remove_colorcarouselimage_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.category')),
            ],
        ),
        migrations.CreateModel(
            name='AdvantageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison', models.CharField(blank=True, max_length=200, null=True)),
                ('lstk', models.CharField(blank=True, max_length=200, null=True)),
                ('traditional_materials', models.CharField(blank=True, max_length=200, null=True)),
                ('advantage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='posts.advantage')),
            ],
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.category')),
            ],
        ),
        migrations.CreateModel(
            name='TabItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('image_title', models.CharField(blank=True, max_length=300, null=True)),
                ('image2', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('tab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='posts.tab')),
            ],
        ),
    ]
