# Generated by Django 5.0.7 on 2024-09-10 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_rename_text_house_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseImageCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.house')),
            ],
        ),
        migrations.CreateModel(
            name='HouseImageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts')),
                ('carousel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.houseimagecarousel')),
            ],
        ),
        migrations.CreateModel(
            name='HouseSchemeCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.house')),
            ],
        ),
        migrations.CreateModel(
            name='HouseSchemeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts')),
                ('carousel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.houseschemecarousel')),
            ],
        ),
    ]
