# Generated by Django 5.0.7 on 2024-09-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_houseimagecarousel_houseimageitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
