# Generated by Django 5.0.7 on 2024-09-11 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_category_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='carousel',
        ),
        migrations.AddField(
            model_name='house',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='posts.category'),
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='posts.house')),
            ],
        ),
        migrations.DeleteModel(
            name='HouseCarousel',
        ),
    ]
