# Generated by Django 5.0.7 on 2024-09-12 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_house_house_cost_house_total_cost_house_work_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseimageitem',
            name='carousel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='posts.houseimagecarousel'),
        ),
        migrations.AlterField(
            model_name='houseschemeitem',
            name='carousel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='posts.houseschemecarousel'),
        ),
    ]
