# Generated by Django 5.0.7 on 2024-09-12 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_alter_houseimageitem_carousel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseimagecarousel',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_image_carousels', to='posts.house'),
        ),
        migrations.AlterField(
            model_name='houseschemecarousel',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_scheme_carousels', to='posts.house'),
        ),
    ]
