# Generated by Django 5.0.7 on 2024-09-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_alter_houseimagecarousel_house_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseschemeitem',
            name='carousel',
        ),
        migrations.AddField(
            model_name='houseimagecarousel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
        migrations.AddField(
            model_name='houseschemecarousel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
        migrations.DeleteModel(
            name='HouseImageItem',
        ),
        migrations.DeleteModel(
            name='HouseSchemeItem',
        ),
    ]
