# Generated by Django 5.0.7 on 2024-09-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0020_remove_houseschemeitem_carousel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("phone_number", models.CharField(max_length=120)),
            ],
        ),
    ]
