# Generated by Django 5.0.7 on 2024-09-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_mainlstkhome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advantage',
            name='category',
        ),
        migrations.AddField(
            model_name='advantage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
        migrations.AddField(
            model_name='unique',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AdvantageItem',
        ),
    ]
