# Generated by Django 5.0.7 on 2024-09-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_remove_advantage_category_advantage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
