# Generated by Django 5.0.7 on 2024-10-05 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_carousel_carouselitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='image',
        ),
        migrations.RemoveField(
            model_name='video',
            name='link',
        ),
        migrations.RemoveField(
            model_name='video',
            name='text',
        ),
        migrations.AddField(
            model_name='video',
            name='link_inst',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='link_youtube',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='VideoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts')),
                ('text', models.TextField(blank=True, null=True)),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='posts.video')),
            ],
        ),
    ]
