# Generated by Django 5.0.7 on 2024-10-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_remove_video_image_remove_video_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='title',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='youtube',
        ),
        migrations.AddField(
            model_name='footer',
            name='title_telegram',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='title_whatsapp',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
