# Generated by Django 5.0.7 on 2024-11-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_comlstk_image_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='navbaritem',
            name='link',
            field=models.CharField(blank=True, null=True),
        ),
    ]
