version: "3.8"

services:
  db:
    image: postgres:14.7
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    command: gunicorn --bind 0.0.0.0:8002 core.wsgi:application

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media

volumes:
  static_volume:
  media_volume:
  db:
